spring:
	profiles:
		active:
		- dev

---

spring:
	profiles: dev        #开发环境
	application:
		name: microservicecloud-config-liuhao-dev
		
---

spring:
	profiles: test
	application:
		name: microservicecloud-config-liuhao-test
# 请保存为UTF-8格式